### PR TITLE
Upgrade to use golang 1.18 and fix readme on how to build locally

### PR DESCRIPTION
**Pull request by hu13**

### CODE REVIEW

**Review by developer-guy — APPROVED** [review]
LGTM

**Comment by developer-guy** [comment]
PTAL @cpanato @gythialy

**Comment by hu13** [comment]
I guess i will have to do this in two PRs.
1. to update go lang 1.18 every where.
2. to update the tag on gocross-builder.

**Comment by cpanato** [comment]
Before we upgrade to go1.18 we will need to create a g1.17 branch we will support 1.17 for a bit more time

thanks for this PR

**Comment by gythialy** [comment]
Duplicate of #107

**Pull request closed without merging**
