### PR TITLE
refactor: build image scripts

### LINKED ISSUE #103: Deprecate docker.pkg.github.com registry in the workflow?
Should we deprecate docker.pkg.github.com registry since it is obsolete and being replaced by ghcr.io?

https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry

### PR DESCRIPTION
**Pull request by gythialy**
- disable docker.pkg.github.com to fix #103 
- bump Debian version to bullseye
- cherry pick 538403c404426f206038095225ce2f6b9adc05f2
- bump golang version to v1.18

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
looks good, just one question why comment on the signing part?

**Comment by gythialy** [comment]
seems not working, I'm not sure what the problem is. @cpanato 

```
Login Succeeded
Generating ephemeral keys...
Retrieving signed certificate...
Non-interactive mode detected, using device flow.
Enter the verification code VPCR-HDMP in your browser at: https://oauth2.sigstore.dev/auth/device?user_code=VPCR-HDMP
Code will be valid for 300 seconds
Error: signing [ghcr.io/gythialy/golang-cross-builder:v1.[17](https://github.com/gythialy/golang-cross/runs/5622104884?check_suite_focus=true#step:7:17).8-1]: getting signer: getting key from Fulcio: retrieving cert: error obtaining token: expired_token
main.go:46: error during command execution: signing [ghcr.io/gythialy/golang-cross-builder:v1.17.8-1]: getting signer: getting key from Fulcio: retrieving cert: error obtaining token: expired_token
Error: Process completed with exit code 1.
```

**Comment by cpanato** [comment]
> seems not working, I'm not sure what the problem is. @cpanato
> 
> ```
> Login Succeeded
> Generating ephemeral keys...
> Retrieving signed certificate...
> Non-interactive mode detected, using device flow.
> Enter the verification code VPCR-HDMP in your browser at: https://oauth2.sigstore.dev/auth/device?user_code=VPCR-HDMP
> Code will be valid for 300 seconds
> Error: signing [ghcr.io/gythialy/golang-cross-builder:v1.[17](https://github.com/gythialy/golang-cross/runs/5622104884?check_suite_focus=true#step:7:17).8-1]: getting signer: getting key from Fulcio: retrieving cert: error obtaining token: expired_token
> main.go:46: error during command execution: signing [ghcr.io/gythialy/golang-cross-builder:v1.17.8-1]: getting signer: getting key from Fulcio: retrieving cert: error obtaining token: expired_token
> Error: Process completed with exit code 1.
> ```

we need to push back the `id-token: write` in the pipeline

**Comment by gythialy** [comment]
According to [this documentation](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/), there is no definition of `id-token`. Is this custom permission?

```
permissions:
  actions: read|write|none
  checks: read|write|none
  contents: read|write|none
  deployments: read|write|none
  issues: read|write|none
  packages: read|write|none
  pull-requests: read|write|none
  repository-projects: read|write|none
  security-events: read|write|none
  statuses: read|write|none
```

**Comment by cpanato** [comment]
> id-token

this is an older doc, that permission was added later, you can check that here https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

but we were signing the image for a long time with that permission enabled :)

**Pull request merged**
